### PR TITLE
Update logic of the seeders to use JSON configurations

### PR DESCRIPTION
**Pull request by vchrombie**
This PR updates the logic of the custom seeders to fetch the data (roles and custom fields) from the JSON files and create them. This allows the users to update the configurations easily.

### CODE REVIEW

**Comment by vchrombie** [comment]
Since we don't have any test suite and have only the docker build and publish tasks, does it make sense to remove the pull request from the workflow condition?

```
  pull_request:
    branches:
      - main
```

**Review by mohan-13 — COMMENTED** [review]
Can we also move the steps which run the seeders to this repository's startup script ? Also the environment variable configuration.

**Comment by vchrombie** [comment]
> Can we also move the steps which run the seeders to this repository's startup script ? Also the environment variable configuration.

I'm also curious about this. If this works, then we can move the dependency from maintaining the crater project.

**Comment by vchrombie** [comment]
Can we merge this PR for now and explore the rest of the improvements?

**Review by N0-man — COMMENTED** [review]
- Update readme
- Remove /package/docker/customStart.sh

**Comment by vchrombie** [comment]
> * Update readme
> * Remove /package/docker/customStart.sh

Since these changes are not related to this PR, I would like to address them in a new PR.

**Comment by vchrombie** [comment]
> * Update readme

Addressed in #3 

> * Remove /package/docker/customStart.sh

Addressed in #2 

@N0-man @mohan-13, can we please merge this PR?

**Review by N0-man — APPROVED** [review]

**Pull request merged**
